/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhgg.views.admin.customer;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import qlbhgg.dao.CustomerDao;
import qlbhgg.models.Customers;

/**
 *
 * @author acer
 */
public class PanelCustomer extends javax.swing.JPanel {

    /**
     * Creates new form PanelCustomer
     */
    
    public ArrayList<Customers> ListCustomers = CustomerDao.findAllCustomer();
    
    public PanelCustomer() throws SQLException{
        initComponents();
        jTableCustomer.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        jTableCustomer.getTableHeader().setOpaque(false);
        jTableCustomer.getTableHeader().setBackground(new Color(102, 178, 255));
        jTableCustomer.setRowHeight(25);
        showTableCustomer();
    }
    
    public void showTableCustomer() {
        jLabelFrameSearchCustomer.setIcon(scaleFrameSearch("/Image/FrameSearch.png"));
        DefaultTableModel tblModel = (DefaultTableModel) jTableCustomer.getModel();
        for (Customers c : ListCustomers) {
            String row[] = {c.getCustomercode(), c.getCustomername(), c.getTradingname(), c.getAddress(), c.getEmail(), c.getPhonenumber()};
            tblModel.addRow(row);
        }
    }
    private ImageIcon scaleFrameSearch(String path) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(280, 30, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        return scaledIcon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDashboardTTKH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        jTextFieldSearchCustomer = new javax.swing.JTextField();
        jLabelSearchCustomer = new javax.swing.JLabel();
        jLabelFrameSearchCustomer = new javax.swing.JLabel();
        jButtonDeleteCustomer = new javax.swing.JButton();
        jButtonAddCustomer = new javax.swing.JButton();
        jButtonEditCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDashboardTTKH.setBackground(new java.awt.Color(255, 255, 255));
        jDashboardTTKH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCustomer.setBackground(new java.awt.Color(255, 255, 255));
        jTableCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableCustomer.setForeground(new java.awt.Color(0, 0, 0));
        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Giao dịch", "Địa chỉ", "Email", "Số điện thoại"
            }
        ));
        jTableCustomer.setFocusable(false);
        jTableCustomer.setRowHeight(25);
        jTableCustomer.setSelectionBackground(new java.awt.Color(215, 220, 222));
        jTableCustomer.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableCustomer.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCustomer);

        jDashboardTTKH.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1330, 790));

        jTextFieldSearchCustomer.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSearchCustomer.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldSearchCustomer.setForeground(new java.awt.Color(120, 120, 120));
        jTextFieldSearchCustomer.setText("Tìm kiếm");
        jTextFieldSearchCustomer.setBorder(null);
        jTextFieldSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldSearchCustomer.setOpaque(false);
        jTextFieldSearchCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchCustomerFocusLost(evt);
            }
        });
        jTextFieldSearchCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchCustomerKeyReleased(evt);
            }
        });
        jDashboardTTKH.add(jTextFieldSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 240, 30));

        jLabelSearchCustomer.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSearchCustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSearchCustomer.setForeground(new java.awt.Color(120, 120, 120));
        jLabelSearchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_20px_1.png"))); // NOI18N
        jLabelSearchCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jDashboardTTKH.add(jLabelSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 30, 30));

        jLabelFrameSearchCustomer.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFrameSearchCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDashboardTTKH.add(jLabelFrameSearchCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 280, 30));

        jButtonDeleteCustomer.setBackground(new java.awt.Color(102, 178, 255));
        jButtonDeleteCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDeleteCustomer.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDeleteCustomer.setText("Xóa");
        jDashboardTTKH.add(jButtonDeleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        jButtonAddCustomer.setBackground(new java.awt.Color(102, 178, 255));
        jButtonAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAddCustomer.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAddCustomer.setText("Thêm");
        jDashboardTTKH.add(jButtonAddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jButtonEditCustomer.setBackground(new java.awt.Color(102, 178, 255));
        jButtonEditCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditCustomer.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditCustomer.setText("Sửa");
        jDashboardTTKH.add(jButtonEditCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        add(jDashboardTTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchCustomerFocusGained
        if (jTextFieldSearchCustomer.getText().equals("Tìm kiếm")) {
            jTextFieldSearchCustomer.setText("");
        }
    }//GEN-LAST:event_jTextFieldSearchCustomerFocusGained

    private void jTextFieldSearchCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchCustomerFocusLost
        if (jTextFieldSearchCustomer.getText().equals("")) {
            jTextFieldSearchCustomer.setText("Tìm kiếm");
        }
    }//GEN-LAST:event_jTextFieldSearchCustomerFocusLost

    private void jTextFieldSearchCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchCustomerKeyReleased
        DefaultTableModel tblModel = (DefaultTableModel) jTableCustomer.getModel();
        int rowcount = tblModel.getRowCount();
        for (int i = rowcount - 1; i >= 0; i--) {
            tblModel.removeRow(i);
        }
        try {
            ListCustomers = CustomerDao.searchCustomer(jTextFieldSearchCustomer.getText());
            showTableCustomer();
        } catch (SQLException ex) {
            Logger.getLogger(PanelCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldSearchCustomerKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCustomer;
    private javax.swing.JButton jButtonDeleteCustomer;
    private javax.swing.JButton jButtonEditCustomer;
    private javax.swing.JPanel jDashboardTTKH;
    private javax.swing.JLabel jLabelFrameSearchCustomer;
    private javax.swing.JLabel jLabelSearchCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTextField jTextFieldSearchCustomer;
    // End of variables declaration//GEN-END:variables
}
