/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhgg.views.staff;

/**
 *
 * @author acer
 */
public class PanelSale extends javax.swing.JPanel {

    /**
     * Creates new form PanelSale
     */
    public PanelSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDashboardQLBH = new javax.swing.JPanel();
        jPanelSelectedProduct = new javax.swing.JPanel();
        jPanelPay = new javax.swing.JPanel();
        jPanelSelectProduct = new javax.swing.JPanel();
        jPanelProduct3 = new javax.swing.JPanel();
        jPanelProduct2 = new javax.swing.JPanel();
        jPanelProduct1 = new javax.swing.JPanel();
        jPanelControlPageBill1 = new javax.swing.JPanel();
        jTextFieldPageBill1 = new javax.swing.JTextField();
        jLabelPageBill1 = new javax.swing.JLabel();
        jLabelRightPageBill1 = new javax.swing.JLabel();
        jLabelLeftPageBill1 = new javax.swing.JLabel();
        jLabelSkipToEndPageBill1 = new javax.swing.JLabel();
        jLabelSkipToStartPageBill1 = new javax.swing.JLabel();
        jLabelSearchBill1 = new javax.swing.JLabel();
        jTextFieldSearchBill1 = new javax.swing.JTextField();
        jLabelFrameSearchBill1 = new javax.swing.JLabel();
        jPanelProduct4 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1330, 870));

        jDashboardQLBH.setBackground(new java.awt.Color(215, 220, 222));
        jDashboardQLBH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSelectedProduct.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelSelectedProductLayout = new javax.swing.GroupLayout(jPanelSelectedProduct);
        jPanelSelectedProduct.setLayout(jPanelSelectedProductLayout);
        jPanelSelectedProductLayout.setHorizontalGroup(
            jPanelSelectedProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelSelectedProductLayout.setVerticalGroup(
            jPanelSelectedProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jDashboardQLBH.add(jPanelSelectedProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 810, 440));

        jPanelPay.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelPayLayout = new javax.swing.GroupLayout(jPanelPay);
        jPanelPay.setLayout(jPanelPayLayout);
        jPanelPayLayout.setHorizontalGroup(
            jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelPayLayout.setVerticalGroup(
            jPanelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jDashboardQLBH.add(jPanelPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 810, 320));

        jPanelSelectProduct.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSelectProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProduct3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProduct3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelProduct3.setPreferredSize(new java.awt.Dimension(150, 165));

        javax.swing.GroupLayout jPanelProduct3Layout = new javax.swing.GroupLayout(jPanelProduct3);
        jPanelProduct3.setLayout(jPanelProduct3Layout);
        jPanelProduct3Layout.setHorizontalGroup(
            jPanelProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanelProduct3Layout.setVerticalGroup(
            jPanelProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanelSelectProduct.add(jPanelProduct3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jPanelProduct2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProduct2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelProduct2.setPreferredSize(new java.awt.Dimension(150, 168));

        javax.swing.GroupLayout jPanelProduct2Layout = new javax.swing.GroupLayout(jPanelProduct2);
        jPanelProduct2.setLayout(jPanelProduct2Layout);
        jPanelProduct2Layout.setHorizontalGroup(
            jPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanelProduct2Layout.setVerticalGroup(
            jPanelProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanelSelectProduct.add(jPanelProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jPanelProduct1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProduct1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelProduct1.setPreferredSize(new java.awt.Dimension(150, 165));

        javax.swing.GroupLayout jPanelProduct1Layout = new javax.swing.GroupLayout(jPanelProduct1);
        jPanelProduct1.setLayout(jPanelProduct1Layout);
        jPanelProduct1Layout.setHorizontalGroup(
            jPanelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanelProduct1Layout.setVerticalGroup(
            jPanelProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanelSelectProduct.add(jPanelProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanelControlPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelControlPageBill1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPageBill1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPageBill1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPageBill1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPageBill1.setText("1");
        jTextFieldPageBill1.setBorder(null);
        jTextFieldPageBill1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPageBill1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPageBill1KeyReleased(evt);
            }
        });
        jPanelControlPageBill1.add(jTextFieldPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, -1));

        jLabelPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPageBill1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPageBill1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPageBill1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPageBill1.setText("/4");
        jPanelControlPageBill1.add(jLabelPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 36, -1));

        jLabelRightPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRightPageBill1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRightPageBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRightPageBill1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_right_20px.png"))); // NOI18N
        jLabelRightPageBill1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRightPageBill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRightPageBill1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRightPageBill1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRightPageBill1MouseExited(evt);
            }
        });
        jPanelControlPageBill1.add(jLabelRightPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabelLeftPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLeftPageBill1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLeftPageBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLeftPageBill1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_left_20px_1.png"))); // NOI18N
        jLabelLeftPageBill1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLeftPageBill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLeftPageBill1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLeftPageBill1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLeftPageBill1MouseExited(evt);
            }
        });
        jPanelControlPageBill1.add(jLabelLeftPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabelSkipToEndPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSkipToEndPageBill1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSkipToEndPageBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSkipToEndPageBill1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_end_20px_1.png"))); // NOI18N
        jLabelSkipToEndPageBill1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSkipToEndPageBill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSkipToEndPageBill1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSkipToEndPageBill1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSkipToEndPageBill1MouseExited(evt);
            }
        });
        jPanelControlPageBill1.add(jLabelSkipToEndPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabelSkipToStartPageBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSkipToStartPageBill1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSkipToStartPageBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSkipToStartPageBill1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_skip_to_start_20px_1.png"))); // NOI18N
        jLabelSkipToStartPageBill1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSkipToStartPageBill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSkipToStartPageBill1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSkipToStartPageBill1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSkipToStartPageBill1MouseExited(evt);
            }
        });
        jPanelControlPageBill1.add(jLabelSkipToStartPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanelSelectProduct.add(jPanelControlPageBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 210, 20));

        jLabelSearchBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSearchBill1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSearchBill1.setForeground(new java.awt.Color(120, 120, 120));
        jLabelSearchBill1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_20px_1.png"))); // NOI18N
        jLabelSearchBill1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanelSelectProduct.add(jLabelSearchBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jTextFieldSearchBill1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSearchBill1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldSearchBill1.setForeground(new java.awt.Color(120, 120, 120));
        jTextFieldSearchBill1.setText("Tìm kiếm");
        jTextFieldSearchBill1.setBorder(null);
        jTextFieldSearchBill1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldSearchBill1.setOpaque(false);
        jTextFieldSearchBill1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchBill1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchBill1FocusLost(evt);
            }
        });
        jTextFieldSearchBill1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchBill1KeyReleased(evt);
            }
        });
        jPanelSelectProduct.add(jTextFieldSearchBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 240, 30));

        jLabelFrameSearchBill1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFrameSearchBill1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelSelectProduct.add(jLabelFrameSearchBill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 30));

        jPanelProduct4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProduct4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelProduct4.setPreferredSize(new java.awt.Dimension(150, 165));

        javax.swing.GroupLayout jPanelProduct4Layout = new javax.swing.GroupLayout(jPanelProduct4);
        jPanelProduct4.setLayout(jPanelProduct4Layout);
        jPanelProduct4Layout.setHorizontalGroup(
            jPanelProduct4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanelProduct4Layout.setVerticalGroup(
            jPanelProduct4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jPanelSelectProduct.add(jPanelProduct4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jDashboardQLBH.add(jPanelSelectProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDashboardQLBH, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDashboardQLBH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPageBill1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPageBill1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPageBill1KeyPressed

    private void jTextFieldPageBill1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPageBill1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPageBill1KeyReleased

    private void jLabelRightPageBill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRightPageBill1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRightPageBill1MouseClicked

    private void jLabelRightPageBill1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRightPageBill1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRightPageBill1MouseEntered

    private void jLabelRightPageBill1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRightPageBill1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRightPageBill1MouseExited

    private void jLabelLeftPageBill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLeftPageBill1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLeftPageBill1MouseClicked

    private void jLabelLeftPageBill1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLeftPageBill1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLeftPageBill1MouseEntered

    private void jLabelLeftPageBill1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLeftPageBill1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLeftPageBill1MouseExited

    private void jLabelSkipToEndPageBill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkipToEndPageBill1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSkipToEndPageBill1MouseClicked

    private void jLabelSkipToEndPageBill1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkipToEndPageBill1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSkipToEndPageBill1MouseEntered

    private void jLabelSkipToEndPageBill1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkipToEndPageBill1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSkipToEndPageBill1MouseExited

    private void jLabelSkipToStartPageBill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkipToStartPageBill1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSkipToStartPageBill1MouseClicked

    private void jLabelSkipToStartPageBill1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkipToStartPageBill1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSkipToStartPageBill1MouseEntered

    private void jLabelSkipToStartPageBill1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSkipToStartPageBill1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelSkipToStartPageBill1MouseExited

    private void jTextFieldSearchBill1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchBill1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchBill1FocusGained

    private void jTextFieldSearchBill1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchBill1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchBill1FocusLost

    private void jTextFieldSearchBill1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchBill1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchBill1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jDashboardQLBH;
    private javax.swing.JLabel jLabelFrameSearchBill1;
    private javax.swing.JLabel jLabelLeftPageBill1;
    private javax.swing.JLabel jLabelPageBill1;
    private javax.swing.JLabel jLabelRightPageBill1;
    private javax.swing.JLabel jLabelSearchBill1;
    private javax.swing.JLabel jLabelSkipToEndPageBill1;
    private javax.swing.JLabel jLabelSkipToStartPageBill1;
    private javax.swing.JPanel jPanelControlPageBill1;
    private javax.swing.JPanel jPanelPay;
    private javax.swing.JPanel jPanelProduct1;
    private javax.swing.JPanel jPanelProduct2;
    private javax.swing.JPanel jPanelProduct3;
    private javax.swing.JPanel jPanelProduct4;
    private javax.swing.JPanel jPanelSelectProduct;
    private javax.swing.JPanel jPanelSelectedProduct;
    private javax.swing.JTextField jTextFieldPageBill1;
    private javax.swing.JTextField jTextFieldSearchBill1;
    // End of variables declaration//GEN-END:variables
}
