/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhgg.Test;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JLabel;

/**
 *
 * @author acer
 */
public final class FormCalendar extends javax.swing.JFrame {
    public final ArrayList<JLabel> ListLabelDays = new ArrayList<JLabel>();
    Calendar cal = new GregorianCalendar();
    public int selectedDay = cal.get(Calendar.DATE);
    public int selectedMonth = cal.get(Calendar.MONTH);
    public int selectedYear = cal.get(Calendar.YEAR);
    public int dayEarlier = 0;

    /**
     * Creates new form FormCalendar
     */
    public FormCalendar() {
        initComponents();
        addLabelDays();
        showCalendar();
    }
    
    
    public void showCalendar(){
        for(int i = 41; i > 34; i--){
            ListLabelDays.get(i).setText("");
        }
        ListLabelDays.get(dayEarlier).setForeground(new java.awt.Color(0, 0, 0));
        
        int cDay = cal.get(Calendar.DATE);
        int cMonth = cal.get(Calendar.MONTH);
        int cYear = cal.get(Calendar.YEAR);
        GregorianCalendar gCal = new GregorianCalendar(selectedYear, selectedMonth, 1);
        int days = gCal.getActualMaximum(Calendar.DATE);
        int startInWeek = gCal.get(Calendar.DAY_OF_WEEK);
        
        gCal = new GregorianCalendar(selectedYear, selectedMonth, days);
        int totalweeks = gCal.getActualMaximum(Calendar.WEEK_OF_MONTH);
        
        int count = 1;
        
        for (int i = 1; i <= totalweeks; i++) {
            for (int j = 1; j <= 7; j++) {
                if (count < startInWeek || (count - startInWeek + 1) > 31) {
                    ListLabelDays.get(count-1).setText("");
                } else {
                    if (cDay == (count - startInWeek + 1) && cMonth == selectedMonth && cYear == selectedYear) {
                        ListLabelDays.get(count-1).setOpaque(true);
                        ListLabelDays.get(count-1).setText(String.valueOf(count - startInWeek + 1));
                        ListLabelDays.get(count-1).setBackground(new java.awt.Color(255, 0, 0));
                        dayEarlier = count - 1;
                   } else {
                        ListLabelDays.get(count-1).setText(String.valueOf(count - startInWeek + 1));
                    }
                }
                count++;
            }
        }
    }
    
    public void addLabelDays(){
        ListLabelDays.add(jLabelDay1);
        ListLabelDays.add(jLabelDay2);
        ListLabelDays.add(jLabelDay3);
        ListLabelDays.add(jLabelDay4);
        ListLabelDays.add(jLabelDay5);
        ListLabelDays.add(jLabelDay6);
        ListLabelDays.add(jLabelDay7);
        ListLabelDays.add(jLabelDay8);
        ListLabelDays.add(jLabelDay9);
        ListLabelDays.add(jLabelDay10);
        ListLabelDays.add(jLabelDay11);
        ListLabelDays.add(jLabelDay12);
        ListLabelDays.add(jLabelDay13);
        ListLabelDays.add(jLabelDay14);
        ListLabelDays.add(jLabelDay15);
        ListLabelDays.add(jLabelDay16);
        ListLabelDays.add(jLabelDay17);
        ListLabelDays.add(jLabelDay18);
        ListLabelDays.add(jLabelDay19);
        ListLabelDays.add(jLabelDay20);
        ListLabelDays.add(jLabelDay21);
        ListLabelDays.add(jLabelDay22);
        ListLabelDays.add(jLabelDay23);
        ListLabelDays.add(jLabelDay24);
        ListLabelDays.add(jLabelDay25);
        ListLabelDays.add(jLabelDay26);
        ListLabelDays.add(jLabelDay27);
        ListLabelDays.add(jLabelDay28);
        ListLabelDays.add(jLabelDay29);
        ListLabelDays.add(jLabelDay30);
        ListLabelDays.add(jLabelDay31);
        ListLabelDays.add(jLabelDay32);
        ListLabelDays.add(jLabelDay33);
        ListLabelDays.add(jLabelDay34);
        ListLabelDays.add(jLabelDay35);
        ListLabelDays.add(jLabelDay36);
        ListLabelDays.add(jLabelDay37);
        ListLabelDays.add(jLabelDay38);
        ListLabelDays.add(jLabelDay39);
        ListLabelDays.add(jLabelDay40);
        ListLabelDays.add(jLabelDay41);
        ListLabelDays.add(jLabelDay42);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelDay1 = new javax.swing.JLabel();
        jLabelDay2 = new javax.swing.JLabel();
        jLabelDay3 = new javax.swing.JLabel();
        jLabelDay4 = new javax.swing.JLabel();
        jLabelDay5 = new javax.swing.JLabel();
        jLabelDay6 = new javax.swing.JLabel();
        jLabelDay7 = new javax.swing.JLabel();
        jLabelDay8 = new javax.swing.JLabel();
        jLabelDay9 = new javax.swing.JLabel();
        jLabelDay10 = new javax.swing.JLabel();
        jLabelDay11 = new javax.swing.JLabel();
        jLabelDay12 = new javax.swing.JLabel();
        jLabelDay13 = new javax.swing.JLabel();
        jLabelDay14 = new javax.swing.JLabel();
        jLabelDay15 = new javax.swing.JLabel();
        jLabelDay16 = new javax.swing.JLabel();
        jLabelDay17 = new javax.swing.JLabel();
        jLabelDay18 = new javax.swing.JLabel();
        jLabelDay19 = new javax.swing.JLabel();
        jLabelDay20 = new javax.swing.JLabel();
        jLabelDay21 = new javax.swing.JLabel();
        jLabelDay22 = new javax.swing.JLabel();
        jLabelDay23 = new javax.swing.JLabel();
        jLabelDay24 = new javax.swing.JLabel();
        jLabelDay25 = new javax.swing.JLabel();
        jLabelDay26 = new javax.swing.JLabel();
        jLabelDay27 = new javax.swing.JLabel();
        jLabelDay28 = new javax.swing.JLabel();
        jLabelDay29 = new javax.swing.JLabel();
        jLabelDay30 = new javax.swing.JLabel();
        jLabelDay31 = new javax.swing.JLabel();
        jLabelDay32 = new javax.swing.JLabel();
        jLabelDay33 = new javax.swing.JLabel();
        jLabelDay34 = new javax.swing.JLabel();
        jLabelDay35 = new javax.swing.JLabel();
        jLabelDay36 = new javax.swing.JLabel();
        jLabelDay37 = new javax.swing.JLabel();
        jLabelDay38 = new javax.swing.JLabel();
        jLabelDay39 = new javax.swing.JLabel();
        jLabelDay40 = new javax.swing.JLabel();
        jLabelDay41 = new javax.swing.JLabel();
        jLabelDay42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelDay1.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay1.setText("N1");
        jLabelDay1.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay2.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay2.setText("N1");
        jLabelDay2.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay3.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay3.setText("N1");
        jLabelDay3.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay4.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay4.setText("N1");
        jLabelDay4.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay5.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay5.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay5.setText("N1");
        jLabelDay5.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay6.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay6.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay6.setText("N1");
        jLabelDay6.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay7.setBackground(new java.awt.Color(143, 143, 182));
        jLabelDay7.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay7.setText("N1");
        jLabelDay7.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay8.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay8.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay8.setText("N1");
        jLabelDay8.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay9.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay9.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay9.setText("N1");
        jLabelDay9.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay10.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay10.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay10.setText("N1");
        jLabelDay10.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay11.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay11.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay11.setText("N1");
        jLabelDay11.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay12.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay12.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay12.setText("N1");
        jLabelDay12.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay13.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay13.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay13.setText("N1");
        jLabelDay13.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay14.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay14.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay14.setText("N1");
        jLabelDay14.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay15.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay15.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay15.setText("N1");
        jLabelDay15.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay16.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay16.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay16.setText("N1");
        jLabelDay16.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay17.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay17.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay17.setText("N1");
        jLabelDay17.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay18.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay18.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay18.setText("N1");
        jLabelDay18.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay19.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay19.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay19.setText("N1");
        jLabelDay19.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay20.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay20.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay20.setText("N1");
        jLabelDay20.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay21.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDay21.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay21.setText("N1");
        jLabelDay21.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay22.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay22.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay22.setText("N1");
        jLabelDay22.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay23.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay23.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay23.setText("N1");
        jLabelDay23.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay24.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay24.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay24.setText("N1");
        jLabelDay24.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay25.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay25.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay25.setText("N1");
        jLabelDay25.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay26.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay26.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay26.setText("N1");
        jLabelDay26.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay27.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay27.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay27.setText("N1");
        jLabelDay27.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay28.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay28.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay28.setText("N1");
        jLabelDay28.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay29.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay29.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay29.setText("N1");
        jLabelDay29.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay30.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay30.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay30.setText("N1");
        jLabelDay30.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay31.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay31.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay31.setText("N1");
        jLabelDay31.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay32.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay32.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay32.setText("N1");
        jLabelDay32.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay33.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay33.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay33.setText("N1");
        jLabelDay33.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay34.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay34.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay34.setText("N1");
        jLabelDay34.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay35.setBackground(new java.awt.Color(204, 204, 255));
        jLabelDay35.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay35.setText("N1");
        jLabelDay35.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay36.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay36.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay36.setText("N1");
        jLabelDay36.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay37.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay37.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay37.setText("N1");
        jLabelDay37.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay38.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay38.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay38.setText("N1");
        jLabelDay38.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay39.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay39.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay39.setText("N1");
        jLabelDay39.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay40.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay40.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay40.setText("N1");
        jLabelDay40.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay41.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay41.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay41.setText("N1");
        jLabelDay41.setPreferredSize(new java.awt.Dimension(30, 30));

        jLabelDay42.setBackground(new java.awt.Color(255, 204, 204));
        jLabelDay42.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDay42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDay42.setText("N1");
        jLabelDay42.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDay15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDay22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDay29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDay36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabelDay42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDay8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDay15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDay22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDay29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDay36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDay42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 270, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCalendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDay1;
    private javax.swing.JLabel jLabelDay10;
    private javax.swing.JLabel jLabelDay11;
    private javax.swing.JLabel jLabelDay12;
    private javax.swing.JLabel jLabelDay13;
    private javax.swing.JLabel jLabelDay14;
    private javax.swing.JLabel jLabelDay15;
    private javax.swing.JLabel jLabelDay16;
    private javax.swing.JLabel jLabelDay17;
    private javax.swing.JLabel jLabelDay18;
    private javax.swing.JLabel jLabelDay19;
    private javax.swing.JLabel jLabelDay2;
    private javax.swing.JLabel jLabelDay20;
    private javax.swing.JLabel jLabelDay21;
    private javax.swing.JLabel jLabelDay22;
    private javax.swing.JLabel jLabelDay23;
    private javax.swing.JLabel jLabelDay24;
    private javax.swing.JLabel jLabelDay25;
    private javax.swing.JLabel jLabelDay26;
    private javax.swing.JLabel jLabelDay27;
    private javax.swing.JLabel jLabelDay28;
    private javax.swing.JLabel jLabelDay29;
    private javax.swing.JLabel jLabelDay3;
    private javax.swing.JLabel jLabelDay30;
    private javax.swing.JLabel jLabelDay31;
    private javax.swing.JLabel jLabelDay32;
    private javax.swing.JLabel jLabelDay33;
    private javax.swing.JLabel jLabelDay34;
    private javax.swing.JLabel jLabelDay35;
    private javax.swing.JLabel jLabelDay36;
    private javax.swing.JLabel jLabelDay37;
    private javax.swing.JLabel jLabelDay38;
    private javax.swing.JLabel jLabelDay39;
    private javax.swing.JLabel jLabelDay4;
    private javax.swing.JLabel jLabelDay40;
    private javax.swing.JLabel jLabelDay41;
    private javax.swing.JLabel jLabelDay42;
    private javax.swing.JLabel jLabelDay5;
    private javax.swing.JLabel jLabelDay6;
    private javax.swing.JLabel jLabelDay7;
    private javax.swing.JLabel jLabelDay8;
    private javax.swing.JLabel jLabelDay9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
