/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhgg.views.common;

import qlbhgg.dao.UsersDao;
import qlbhgg.models.Users;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author acer
 */
public class ConfirmDeleteStaff extends javax.swing.JFrame {
    public Users user;
    /**
     * Creates new form ConfirmOperations
     */
    public ConfirmDeleteStaff(Users u) {
        initComponents();
        user = u;
        jLabelText.setText("<html>Bạn có chắc chắn muốn xóa tài khoản: " + u.getFullname() + "?</html>");
        jLabelButtonOk.setIcon(scaleImage("/Image/SignButtonBlue.png"));
        jLabelButtonCancel.setIcon(scaleImage("/Image/SignButtonBlue.png"));
        jLabelButtonOk1.setIcon(scaleImage("/Image/SignButtonBlue.png"));
        jLabelButtonOk1.setVisible(false);
        jLabelOk1.setVisible(false);
    }

    private ImageIcon scaleImage(String path) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(100, 40, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        return scaledIcon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelOk1 = new javax.swing.JLabel();
        jLabelButtonOk1 = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();
        jLabelCancel = new javax.swing.JLabel();
        jLabelOk = new javax.swing.JLabel();
        jLabelButtonOk = new javax.swing.JLabel();
        jLabelButtonCancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOk1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOk1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOk1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelOk1.setText("OK");
        jLabelOk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelOk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 151, -1, -1));

        jLabelButtonOk1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelButtonOk1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonOk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonOk1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonOk1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonOk1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonOk1MouseExited(evt);
            }
        });
        jPanel1.add(jLabelButtonOk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 100, 40));

        jLabelText.setBackground(new java.awt.Color(255, 255, 255));
        jLabelText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelText.setText("Bạn có chắc chắn muốn cho phép tài khoản này hoạt động?");
        jPanel1.add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 314, 127));

        jLabelCancel.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCancel.setText("Hủy");
        jLabelCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 151, -1, -1));

        jLabelOk.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOk.setForeground(new java.awt.Color(0, 0, 0));
        jLabelOk.setText("Xác nhận");
        jLabelOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 151, -1, -1));

        jLabelButtonOk.setBackground(new java.awt.Color(255, 255, 255));
        jLabelButtonOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonOkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonOkMouseExited(evt);
            }
        });
        jPanel1.add(jLabelButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 40));

        jLabelButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jLabelButtonCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonCancelMouseExited(evt);
            }
        });
        jPanel1.add(jLabelButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelButtonOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonOkMouseEntered
        jLabelButtonOk.setIcon(scaleImage("/Image/SignButtonGray.png"));
    }//GEN-LAST:event_jLabelButtonOkMouseEntered

    private void jLabelButtonOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonOkMouseExited
        jLabelButtonOk.setIcon(scaleImage("/Image/SignButtonBlue.png"));
    }//GEN-LAST:event_jLabelButtonOkMouseExited

    private void jLabelButtonCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCancelMouseEntered
        jLabelButtonCancel.setIcon(scaleImage("/Image/SignButtonGray.png"));
    }//GEN-LAST:event_jLabelButtonCancelMouseEntered

    private void jLabelButtonCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCancelMouseExited
        jLabelButtonCancel.setIcon(scaleImage("/Image/SignButtonBlue.png"));
    }//GEN-LAST:event_jLabelButtonCancelMouseExited

    private void jLabelButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonCancelMouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jLabelButtonCancelMouseClicked

    private void jLabelButtonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonOkMouseClicked
        
        UsersDao.deleteStaff(user);
        jLabelText.setText("<html>Thao tác thành công!</html>");
        jLabelButtonCancel.setVisible(false);
        jLabelCancel.setVisible(false);
        jLabelButtonOk.setVisible(false);
        jLabelOk.setVisible(false);
        jLabelButtonOk1.setVisible(true);
        jLabelOk1.setVisible(true);
    }//GEN-LAST:event_jLabelButtonOkMouseClicked

    private void jLabelButtonOk1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonOk1MouseClicked
        
        this.dispose();
    }//GEN-LAST:event_jLabelButtonOk1MouseClicked

    private void jLabelButtonOk1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonOk1MouseEntered
        
        jLabelButtonOk1.setIcon(scaleImage("/Image/SignButtonGray.png"));
    }//GEN-LAST:event_jLabelButtonOk1MouseEntered

    private void jLabelButtonOk1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonOk1MouseExited
        
        jLabelButtonOk1.setIcon(scaleImage("/Image/SignButtonBlue.png"));
    }//GEN-LAST:event_jLabelButtonOk1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmDeleteStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmDeleteStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmDeleteStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmDeleteStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelButtonCancel;
    private javax.swing.JLabel jLabelButtonOk;
    private javax.swing.JLabel jLabelButtonOk1;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelOk;
    private javax.swing.JLabel jLabelOk1;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
